chore: remove deprecated husky shim and inline hooks
Signed-off-by: MB Swirlds <127280401+mb-swirlds@users.noreply.github.com>
Signed-off-by: MB Swirlds <michael.bennett@hashgraph.com>

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,11 +1,11 @@
 #!/usr/bin/env sh
-. "$(dirname -- "$0")/_/husky.sh"
+set -e
 
-echo "husky - pre-commit running lint-staged"
-npx lint-staged
-status=$?
-if [ $status -ne 0 ]; then
-	echo "husky - pre-commit failed (code $status)"
-	exit $status
+echo "pre-commit: running lint-staged"
+if npx lint-staged; then
+	echo "pre-commit: success"
+else
+	code=$?
+	echo "pre-commit: failed (code $code)"
+	exit $code
 fi
-echo "husky - pre-commit passed"
diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,11 +1,11 @@
 #!/usr/bin/env sh
-. "$(dirname -- "$0")/_/husky.sh"
+set -e
 
-echo "husky - pre-push running tests"
-npm run test:all
-status=$?
-if [ $status -ne 0 ]; then
-	echo "husky - pre-push failed (code $status)"
-	exit $status
+echo "pre-push: running tests (npm run test:all)"
+if npm run test:all; then
+	echo "pre-push: success"
+else
+	code=$?
+	echo "pre-push: failed (code $code)"
+	exit $code
 fi
-echo "husky - pre-push passed"
